[project]
name = "test-project"
version = "0.1.0"
description = "This is for test project"
authors = [
    {name = "Jan Rambo",email = "rambo@abc.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black (>=22.8.0,<23.0.0)"
]

[tool.poetry]
packages = [{include = "test_project", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
